force-app/main/default/objects/Case/fields/Product_Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Product_Purchase_Date__c</fullName>
    <label>Product Purchase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product_Total_Warranty_Days__c.field-meta.xml
<CustomField>
    <fullName>Product_Total_Warranty_Days__c</fullName>
    <label>Product Total Warranty Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Warranty_Summary__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Summary__c</fullName>
    <label>Warranty Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CaseTrigger_Companion.cls
/**
* Reis Taylor
* Last Modified 6/7/2022
*/

public with sharing class CaseTrigger_Companion {
 
    public static void caseWarrantyDescription(List<Case> caseTriggerList) {

        for (Case myCase : caseTriggerList) {
                
            String caseProduct         = myCase.Product__c;
            System.debug(caseProduct);
            String purchaseDate        = myCase.Product_Purchase_Date__c.format();
            System.debug(purchaseDate);
            String createdDate         = DateTime.now().format();
            System.debug(createdDate);
            Integer warrantyDays       = myCase.Product_Total_Warranty_Days__c.intValue();

            Decimal warrantyPercentage = (100-(100*(myCase.Product_Purchase_Date__c.daysBetween(
                                        Date.today())/(myCase.Product_Total_Warranty_Days__c))))
                                        .setScale(2);
            System.debug(warrantyPercentage);
            
            myCase.Warranty_Summary__c = 'Summary of Customer Warranty: ' 
                                    + 'This case was created on ' 
                                    +  createdDate + ' '  +
                                    +  myCase.Product__c  + ' was purchased on ' 
                                    +  purchaseDate       + ', Standard Earth Time-Space.'
                                    + 'The warranty has ' + warrantyPercentage + '% power level remaining.';
        System.debug(myCase.Warranty_Summary__c);
        }        
    }

}