force-app/main/default/objects/Case/fields/Product_Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Product_Purchase_Date__c</fullName>
    <label>Product Purchase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product_Total_Warranty_Days__c.field-meta.xml
<CustomField>
    <fullName>Product_Total_Warranty_Days__c</fullName>
    <label>Product Total Warranty Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseTriggerTest.cls
/**
*Reis Taylor
*Last Modified: 6/7
*100% Code Coverage
*See comments in CaseTrigger
 */

@isTest
public class CaseTriggerTest {
 
   @isTest static void newCase() {
        Test.startTest();
        Case kase = new Case();
        kase.Status = 'working';
        kase.Origin = 'web';
        kase.Product_Purchase_Date__c        = Date.today();
        kase.Product_Total_Warranty_Days__c  = 90; 
        insert kase;
       Test.stopTest();
    }
}