force-app/main/default/objects/Opp_FollowUp__e/Opp_FollowUp__e.object-meta.xml
<CustomObject>
    <description>Follow up on new opps for 1 week from creation date.</description>
    <label>Opp FollowUp</label>
    <pluralLabel>Opp FollowUps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opp_FollowUp__e/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <label>Follow Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opp_FollowUp__e/fields/New_Opp__c.field-meta.xml
<CustomField>
    <fullName>New_Opp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Opp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OppFollowUpTest.cls
/* Author: Trenton Teasdale
  Last Modified: 6/7/22
	Test for platform event
*/

@isTest
public class OppFollowUpTest {
    @isTest static void test(){
            Date dueDate = (Date.today())+7;
        Opp_FollowUp__e opp = new Opp_FollowUp__e(
            New_Opp__c = true,
            Follow_Up_Date__c = dueDate);
        Test.startTest();
       	Database.SaveResult sr = EventBus.publish(opp);
        Test.stopTest();
        
        System.assertEquals(true, sr.isSuccess());
        
        List<Task> tasks = [SELECT Id FROM Task];
        System.assertEquals(1, tasks.size());
}
}