force-app/main/default/objects/Opp_FollowUp__e/Opp_FollowUp__e.object-meta.xml
<CustomObject>
    <description>Follow up on new opps for 1 week from creation date.</description>
    <label>Opp FollowUp</label>
    <pluralLabel>Opp FollowUps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opp_FollowUp__e/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <label>Follow Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opp_FollowUp__e/fields/New_Opp__c.field-meta.xml
<CustomField>
    <fullName>New_Opp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Opp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OppFollowUpOnOpp_Helper.cls
// OppFollowUpOnOpp_Helper
// Matt McCain
// Created Date 6/7/22
// Modified Date 6/7/22
// This Helper sets a follow up date and
// publishes the Opportunity Event


public class OppFollowUpOnOpp_Helper {

    public OppFollowUpOnOpp_Helper() {

    }

    public static void createEvent(List<Opportunity> oppList) {
        for (Opportunity opp : oppList) {

            Date dueDate = (Date.today()+7);
            Opp_FollowUp__e oppFollow = new Opp_FollowUp__e(
            New_Opp__c = true,
            Follow_Up_Date__c = dueDate);
            Eventbus.publish(oppFollow);
        }
    }
}